# Generated by Django 4.0.5 on 2022-06-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('address', models.CharField(max_length=122)),
                ('phoneno', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=9)),
                ('pin', models.CharField(max_length=6)),
            ],
        ),
    ]
