# Generated by Django 4.0.5 on 2022-06-14 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='password',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='state',
        ),
    ]
